# Generated by Django 5.1.1 on 2024-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='заголовок')),
                ('text', models.TextField(verbose_name='текст')),
                ('images', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='Превью блога')),
                ('blog_date', models.DateField(blank=True, null=True, verbose_name='Дата публикации')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Блог',
                'verbose_name_plural': 'Блоги',
            },
        ),
    ]
